version: 3.8

services:
    caddy:
        image: caddy:alpine
        container_name: caddy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./caddy/data:/data
            - ./caddy/config:/config
            - ./Caddyfile:/etc/caddy/Caddyfile
    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: always
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer/data:/data
